name: NTIRE
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch=2.1.2
  - pytorch::torchvision
  # - nvidia::pytorch-cuda=11.8
  - conda-forge::cudatoolkit=11.8
  - conda-forge::opencv
  - conda-forge::matplotlib
  - matplotlib
  - pip
  - pip:
    - gdown
    - fire
